apiVersion : apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
  labels:
    app: apigateway 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway 
    spec:
      containers:
        - name: apigateway 
          image: razvan426823wedeliver.azurecr.io/apigateway
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING
          ports:
            - containerPort: 8080