apiVersion: v1
kind: Service
metadata:
    name: apigateway
spec:
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 80 
          targetPort: 8080
    selector:
        app: apigateway